// @generated by expo-module-scripts
const { defineConfig } = require('eslint/config');
const baseConfig = require('expo-module-scripts/eslint.config.base');

module.exports = defineConfig([
  baseConfig,
  {
    rules: {
      // Biome is the source of truth for formatting in this repo.
      'prettier/prettier': 'off',
    },
  },
]);
