#!/usr/bin/env node
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

execSync('bunx expo-module prepare', { stdio: 'inherit' });

const eslintConfig = `// @generated by expo-module-scripts\nconst { defineConfig } = require('eslint/config');\nconst baseConfig = require('expo-module-scripts/eslint.config.base');\n\nmodule.exports = defineConfig([\n  baseConfig,\n  {\n    rules: {\n      // Biome is the source of truth for formatting in this repo.\n      'prettier/prettier': 'off',\n    },\n  },\n]);\n`;

writeFileSync(resolve(process.cwd(), 'eslint.config.js'), eslintConfig);
